[build]
  base = "my-react-Nicholas"
  command = "npm run build"
  publish = "my-react-Nicholas/dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200